import Head from 'next/head'
import Image from 'next/legacy/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Banner from '../components/Banner'
import SmallCard from '../components/SmallCard'
import MediumCard from '../components/MediumCard'
import LargeCard from '../components/LargeCard'
import Footer from '../components/Footer'


const inter = Inter({ subsets: ['latin'] })

export default function Home({ exploreData, cardsData }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      {/* Explore Nearby */}
      <main className=' max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>
          {/* pull server endpoint */}
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
          {exploreData?.map((item) => (
            <SmallCard  img={item.img} 
                        key={item.location}
                        location={item.location}
                        distance={item.distance} />
          ))}
        </div>
        </section>

        {/* Live Anywhere */}
        <section>
          <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>

          <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 ml-3'>
            {cardsData?.map(({ img, title}) => (
              <MediumCard img={img}
                          title={title}
                          key={img}/>
            ))}
          </div>
        </section>

        {/* Large Card For Bottom */}
        <LargeCard
          img='https://a0.muscache.com/im/pictures/2da67c1c-0c61-4629-8798-1d4de1ac9291.jpg?im_w=1440'
          title="The Great Outdoors"
          description="Curated by AirBnb."
          buttonText="Get Inspired"
         />
      </main>

      <Footer />
    </div>
  )
}




// pulling in the static props for the airbnb location list
export async function getStaticProps() {
  // airbnb location list
  const exploreData = await fetch('https://www.jsonkeeper.com/b/4G1G').
  then(
    (res) => res.json()
);


//Live Anywhere List
    const cardsData = await (await fetch('https://www.jsonkeeper.com/b/VHHT'). 
    then(
      (res) => res.json()
    ))

  return {
    props: {
      exploreData,
      cardsData
    }
  }
  }